In [15]:
# c0202_Numpy基础数据结构_课程作业

# 作业1：分别按照要求，生成一个一维数组、二维数组，并且查看其shape

import numpy as np
ar1 = np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(ar1,ar1.shape)

ar2 = np.array([[0,1,2,3,4,5,],('a','b','c','d','e','f'),(True,False,True,False,True,False)])
print(ar2,ar2.shape)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}] (6,)
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'False']] (3, 6)


In [19]:
# 作业2：生成一个一维数组，起始值为5，终点值为15，样本数为10个

ar3 = np.linspace(5,15,10,dtype=np.int,endpoint=False)
print(ar3)

[ 5  6  7  8  9 10 11 12 13 14]


In [24]:
# 作业3：按照要求创建以下数组

ar4 = np.zeros((4,4))
print(ar4)

ar5 = np.ones((2,3))
print(ar5)

ar6 = np.eye(3)
print(ar6)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [9]:
# c0203_Numpy索引及切片  课程作业
# 作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少

import numpy as np
ar7 = np.arange(25).reshape(5,5)
print(ar7)
print(ar7[4])
print(ar7[:2,3:])
print(ar7[3][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [16]:
# 作业2：按照要求创建数组，筛选出元素值大于5的值并生成新的数组
ar8 = np.arange(10).reshape(2,5)
m = ar8 > 5
print(m)
print(ar8[m])

[[False False False False False]
 [False  True  True  True  True]]
[6 7 8 9]
