In [15]:
# c0202_Numpy基础数据结构_课程作业

# 作业1：分别按照要求，生成一个一维数组、二维数组，并且查看其shape

import numpy as np
ar1 = np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(ar1,ar1.shape)

ar2 = np.array([[0,1,2,3,4,5,],('a','b','c','d','e','f'),(True,False,True,False,True,False)])
print(ar2,ar2.shape)

[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'one': 100}] (6,)
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'False' 'True' 'False']] (3, 6)


In [19]:
# 作业2：生成一个一维数组，起始值为5，终点值为15，样本数为10个

ar3 = np.linspace(5,15,10,dtype=np.int,endpoint=False)
print(ar3)

[ 5  6  7  8  9 10 11 12 13 14]


In [24]:
# 作业3：按照要求创建以下数组

ar4 = np.zeros((4,4))
print(ar4)

ar5 = np.ones((2,3))
print(ar5)

ar6 = np.eye(3)
print(ar6)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
